### ISSUE TITLE
MultiMC5 SSL errors w/ Debian 9

### ISSUE THREAD

**Issue by ReillyBrogan** [MultiMC/MultiMC5#1816]
System Information
-----------------------------
MultiMC version:
0.5.0-887
Operating System:
Debian 9 Stretch
Summary of the issue or suggestion:
----------------------------------------------
Attempting to add a Mojang account to the client fails with SSL errors. The following lines are displayed in the log files when this happens indicating an issue with the OpenSSL libraries:
```
29.571 W QSslSocket: cannot call unresolved function SSLv23_client_method
29.571 W QSslSocket: cannot call unresolved function SSL_library_init
```

Additionally the RSS feeds fail to download for the same reason, and display the same log error.

What should happen:
------------------------------
Mojang account should download and RSS feeds should populate with news.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install MultiMC5 on Debian 9

2. Attempt to add Mojang Account.

Suspected cause:
---------------------------
It looks like the Debian OpenSSL libraries are to blame for this issue. Following a similar issue [here](https://confluence.atlassian.com/hipchatkb/hipchat4-debian-client-doesn-t-connect-859526103.html)
leads to a temporary solution of running the following commands in the ./bin directory:
```bash
ln -s /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
ln -s libssl.so.1.0.2 libssl.so
```

Logs/Screenshots:
----------------------------
https://paste.ee/p/NcOL9

**Comment by QuImUfu** [comment]
Try to remove/move every library (.so) in the bin subfolder except the ones starting with libMultiMC_ .
This forces MMC to use your system libraries which are working properly with new versions of OpenSSL. 
This will be the default in future MMC versions, iirc.
see: #1784

**Comment by ReillyBrogan** [comment]
Unfortunately that doesn't seem to work as libxcb-sync doesn't seem to be present in the Debian repositories and libxcb-sync1 (which is available) doesn't seem to be the same thing. I tried installing libxcb-sync-dev and libxcb-sync1-dbg as well to no avail.

I tried again this time leaving libxcb-sync along with the libMultiMC files and I was able to launch the client, add my Mojang account and launch the game although It crashed shortly thereafter. Logs: https://paste.ee/p/6zgHN

Could this possibly be an incompatibility between the bundled libxcb-sync and the rest of the system libraries or do I need to copy in another one of the bundled libraries? The separate MultiMC install I have that I copied in the system libssl libraries into is working perfectly and allows me to launch and play a modpack so I know that MultiMC is capable of working on this system.

**Comment by QuImUfu** [comment]
You solution is most likely working perfectly. (if there would be a problem with the libraries it imo would crash MMC, not minecraft)

Could you post the Minecraft log? 
Maybe it's a completely different problem as the Launcher log doesn't indicate anything special.
It is however very weird that the same instance does work on the other installation. 
The MC log will tell us more about this issue.

**Comment by ReillyBrogan** [comment]
I think it was an unrelated issue as it went away on reboot (Debian 9 is still not considered "stable"). Deleting everything except for the libMultiMC and libxcb libraries allowed me to successfully launch Minecraft.

As Kali Linux is based on Debian Linux and the issues are identical you can probably merge this with #1784

**Comment by krrg** [comment]
For the record, I am experiencing an identical issue on Fedora 26.  I experimented with different permutations of deleting the bundled libraries to no avail, but kept getting errors described in https://github.com/MultiMC/MultiMC5/issues/1979.  

Solution for Fedora 26 was to install `compat-openssl10` package, then symlink, similar to what was described above.

  ln -s /lib64/libcrypto.so.10 libcrypto.so
  ln -s /lib64/libssl.so.10 libssl.so

**Comment by idkCpp** [comment]
I am experiencing this issue on Debian 9 Stretch and solved it by installing `libssl1.0-dev`.

**Comment by stephen-smith** [comment]
Getting this on:

```
% uname -a
Linux monster 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux
% cat /etc/debian_version
9.4
```

Removing libQt5* and libstc++* from bin/ fixes it for me, but MultiMC puts them back (and immediately breaks) if I let the in-app update run.

**Comment by stephen-smith** [comment]
Still fails on current stable:

```
% MultiMC -V
...
No missing dependencies found.
Version 0.6.2-1137
Git 6284f070c19053ae2bcf26dd9bccac2e0d35477f
% cat /etc/debian_version
9.5
```

**Comment by stephen-smith** [comment]
Logs of this issue from latest stable: https://pastebin.com/3NJNHQCt

**Comment by nift4** [comment]
Ubuntu 19.04 - fixed with `rm ~/.local/share/multimc/bin/libQt5*`

**Comment by svenhjol** [comment]
@nift4 your solution worked after running `apt install libqt5xml5` in case anyone else has trouble on Ubuntu 19.04

**Comment by JakeMoe** [comment]
FWIW, `rm ~/.local/share/multimc/bin/libQt5*` worked on Lubuntu 19.04 as well.  I tried to `apt install libqt5xml5`, but it was already installed and up-to-date.  Thanks for the fix.  :-)

**Comment by AriaanBruinsma** [comment]
> Ubuntu 19.04 - fixed with `rm ~/.local/share/multimc/bin/libQt5*`

This fixed it for me on Pop!_OS 19.04

**Comment by RyanmFisher** [comment]
> Ubuntu 19.04 - fixed with `rm ~/.local/share/multimc/bin/libQt5*`

Running Ubuntu 19.04 running that causes MultiMC to no longer open at all. even removing the package for multimc does not fix this I had to manually delete the ~/.local/share/multimc folder as removing the package did not for some reason and reinstall from the deb still not working back to square 1

**Comment by nift4** [comment]
Tried https://github.com/MultiMC/MultiMC5/issues/1816#issuecomment-490299867 ?

**Comment by RyanmFisher** [comment]
> Tried [#1816 (comment)](https://github.com/MultiMC/MultiMC5/issues/1816#issuecomment-490299867) ?

Running the latest version of the package

**Comment by nift4** [comment]
@RyanmFisher Ok good

**Comment by peterix** [comment]
Resolving as fixed, will be in stable release later today.
